INSERT INTO WASTE_CATEGORIES(NAME) VALUES ('TOXIC WASTE');
INSERT INTO MATERIALS(WASTE_ID, NAME) VALUES (1,'masepa');

INSERT INTO GUIDELINES(MATERIAL_ID, GUIDELINE) VALUES (1,'throw away'), (1,'bury it');