    create table if not exists RECYCLING_TIPS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TIP TEXT NOT NULL UNIQUE
);

create table if not exists WASTE_CATEGORIES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL UNIQUE
);

create table if not exists MATERIALS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    WASTE_ID INT NOT NULL,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    FOREIGN KEY (WASTE_ID) REFERENCES WASTE_CATEGORIES(ID) ON DELETE CASCADE
);

create table if not exists GUIDELINES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MATERIAL_ID INT NOT NULL,
    GUIDELINE TEXT NOT NULL,
    FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIALS(ID) ON DELETE CASCADE
);